spring.application.name=demo

spring.datasource.url=jdbc:mysql://localhost:3306/doctor_patient_db
spring.datasource.username=root
spring.datasource.password=your_pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.jwt.secret=your_key
